# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.mylibrary: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
#For test
spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 0
      database: loans-db
      authentication-database: admin
      auto-index-creation: true

#for flapdoodle
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

app:
  books-service:
    host: catalogs-service
    port: 7001
  members-service:
    host: members-service
    port: 7002
  fines-service:
    host: fines-service
    port: 7003
---

# for docker

spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      username: user
      password: pwd
      database: loans-db
      host: mongodb
      port: 27017
      authentication-database: admin
      auto-index-creation: true

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000

app:
  catalogs-service:
    host: catalogs-service
    port: 8080
  members-service:
    host: members-service
    port: 8080
  fines-service:
    host: fines-service
    port: 8080